@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList *-right-> "*" Tag
UniquePersonList o-right-> Person

Person -up-> "           *" TagName

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> TelegramAddress

Tag *-right-> TagName
Tag *-right-> "*" TagTask
Tag *-right-> MeetingLink
TagName -[hidden]right-> TagTask
TagTask -[hidden]right-> MeetingLink

@enduml
