@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
Interface ReadOnlyProjact <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Class Projact
Class ReadOnlyProjact
Class Model
Class ModelManager
Class UserPrefs

Package Person\n {
Class Person
Class Email
Class Name
Class Phone
Class TelegramAddress
Class UniquePersonList
}

Package Tag\n {
Class Tag
Class TagName
Class MeetingLink
Class UniqueTagList
}

Package TagTask\n {
Class TagTask
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Projact .right.|> ReadOnlyProjact

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o-down-> "1" Projact
ModelManager o-down-> "1" UserPrefs
UserPrefs .left.|> ReadOnlyUserPrefs

Projact *--> "1" UniquePersonList
UniquePersonList o--> "*" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> TelegramAddress
Person --> "*" TagName

Name -[hidden]right-> Phone
Phone -[hidden]right-> TelegramAddress
TelegramAddress -[hidden]right-> Email

Projact *--> "1" UniqueTagList
UniqueTagList o--> "*" Tag
Tag *--> TagName
Tag *--> MeetingLink
Tag *--> "*" TagTask

@enduml
