@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ProjactStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonProjactStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> ProjactStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonProjactStorage .left.|> ProjactStorage
JsonProjactStorage .down.> JsonSerializableProjact
JsonSerializableProjact .right.> JsonAdaptedPerson
JsonSerializableProjact .left.> JsonAdaptedTag
JsonAdaptedTag .down.> JsonAdaptedTagTask
@enduml
