@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Package Storage {
Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ProjactStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonProjactStorage
Class JsonSerializableProjact
Class JsonAdaptedTag
Class JsonAdaptedTagTask
Class JsonAdaptedPerson
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager o--> UserPrefsStorage
StorageManager o--> ProjactStorage

JsonUserPrefsStorage .right.|> UserPrefsStorage
JsonProjactStorage .left.|> ProjactStorage
JsonProjactStorage .down.> JsonSerializableProjact
JsonSerializableProjact ..> JsonAdaptedPerson
JsonSerializableProjact ..> JsonAdaptedTag
JsonAdaptedTag .down.> JsonAdaptedTagTask
@enduml
